config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up, to: 'votes#vote_up'
      post :vote_down, to: 'votes#vote_down'
      delete :unvote, to: 'votes#unvote'
    end
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        patch :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :badges, only: %i[destroy index]
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  scope :kept, -> { where(discarded_at: nil) }

  def soft_delete
    update(discarded_at: Time.current)
  end

  def mark_as_best
    question.update(best_answer_id: id)
    award_badge_to_user
  end

  private

  def award_badge_to_user
    return unless question.badge

    user.badges << question.badge
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy mark_as_best]
  before_action :set_question, only: %i[index new create]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @answers = @question.answers.kept
  end

  def new
    @answer = @question.answers.new
    @answer.links.build # or @answer.links.new
  end

  def show; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      render_success_message(@answer)
    else
      render_error_message(@answer)
    end
  end

  def edit; end

  def update
    @answer.update(answer_params) if current_user.author?(@answer)

    set_answers_data
  end

  def destroy
    @answer.soft_delete if current_user.author?(@answer)
  end

  def mark_as_best
    @answer.mark_as_best

    set_answers_data
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_answers_data
    @question = @answer.question
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @best_answer).kept
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   files: [],
                                   links_attributes: %i[id name url _destroy])
  end

  def render_success_message(answer)
    attachments = format_attachments(answer.files)

    render json: { id: answer.id, body: answer.body, attachments: }, status: :created
  end

  def render_error_message(answer)
    render json: answer.errors.full_messages, status: :unprocessable_entity
  end

  def format_attachments(files)
    files.map do |file|
      {
        url: url_for(file),
        filename: file.filename.to_s
      }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/shared/answers/_answer_attachment.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div id="file_container_#{file.id}" class="file-container"
      - if file.representable?
        = link_to url_for(file) do
          = image_tag file.representation(resize_to_limit: [50, 50]).processed
      - else
        p= link_to file.filename.to_s, url_for(file)

      - if author?(current_user, resource)
        = button_to "Remove file",
                attachment_path(file),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                remote: true

app/views/shared/answers/_answer_attachment_check.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div id="file_container_#{file.id}" class="file-container"
      - if file.representable?
        = link_to url_for(file) do
          = image_tag file.representation(resize_to_limit: [50, 50]).processed
      - else
        p= link_to file.filename.to_s, url_for(file)

      - if is_author?(current_user, resource)
        = button_to "Remove file",
                attachment_path(file),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                remote: true

app/views/shared/answers/_answer_controls.html.slim
- if author?(current_user, answer)
  = button_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
  = button_to 'Delete answer', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, remote: true

- if question_author?(current_user, question, best_answer, answer)
  = button_to 'Mark as best answer', mark_as_best_answer_path(answer), method: :patch, remote: true

= form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |form|
  .answer-errors
    = render 'shared/errors', resource: answer
  .field
    p
      = form.label :body, 'Your answer'
      = form.text_area :body
    - answer.files.each do |file|
      = hidden_field_tag 'answer[files][]', file.signed_id

    p
      = form.label :files
      = form.file_field :files, multiple: true

    - if answer.links.any?
      p Links:
      = form.fields_for :links do |l|
        = render 'link_fields', f: l
    .links
      = link_to_add_association 'Add link', form, :links

  .actions
    = form.submit 'Save'