config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up, to: 'votes#vote_up'
      post :vote_down, to: 'votes#vote_down'
      delete :unvote, to: 'votes#unvote'
    end
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        patch :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :badges, only: %i[destroy index]
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_one :badge, -> { kept }, dependent: :destroy

  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :badge, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :body, presence: true

  scope :kept, -> { where(discarded_at: nil) }

  def soft_delete
    update(discarded_at: Time.current)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show edit update destroy]

  def index
    @questions = Question.kept
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question has been created'
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answer.links.build
    @best_answer = @question.best_answer
    @best_answer = nil if @best_answer&.discarded_at.present?
    @other_answers = @question.answers.where.not(id: @best_answer).kept
    @badge = @question.badge
  end

  def new
    @question = Question.new
    @question.build_badge
    @question.links.build # or @question.links.new
  end

  def edit; end

  def update
    @question.update(question_params) if current_user.author?(@question)
  end

  def destroy
    @question.soft_delete if current_user.author?(@question)
    redirect_to questions_path, notice: 'Your question has been deleted'
  end

  private

  def find_question
    @question = Question.with_attached_files.includes(:links).find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: %i[id name url _destroy],
      badge_attributes: %i[id name badge_image _destroy]
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with(model: question, local: true, data: { turbo: false }) do |form|
  .question-errors
    = render 'shared/errors', resource: question
  .field
    p
      = form.label :title, 'Title'
      = form.text_field :title
    p
      = form.label :body, 'Body'
      = form.text_area :body

    .file_fields
      p File:
      = form.label :files
      = form.file_field :files, multiple: true

    .badge_fields
      p Badge:
      = form.fields_for :badge do |badge_form|
        p
          = badge_form.label :name, 'Badge Name'
          = badge_form.text_field :name
        p
          = badge_form.label :badge_image, 'Upload Badge'
          = badge_form.file_field :badge_image

    .links
      = link_to_add_association 'Add link', form, :links

  .actions
    p
      = form.submit 'Ask'

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name

    = f.label :url, 'Url'
    = f.text_field :url
  = link_to_remove_association 'Remove link', f

app/views/questions/_question.html.slim
.div class="question" data-question-id=question.id
  h1= question.title
  p= question.body
  p
    | Rating:
  = render "shared/votes", resource: question

  = render 'shared/files_attachment', resource: question

  - if author?(current_user, question)
    = render 'shared/questions/badge_attachment', badge: badge

  = render 'shared/links_attachment', resource: question

  p
  - if author?(current_user, question)
    = button_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = button_to 'Delete', question_path(question), method: :delete

  = form_with model: question, local: false, class: 'hidden edit-question-form', html: { id: "edit-question-#{question.id}" } do |form|
    .question-errors
      = render 'shared/errors', resource: question
    = render 'shared/questions/edit_form', form: form, question: question

app/views/questions/index.html.slim
p = link_to t('New Question'), new_question_path, class: 'btn btn-primary'

h2 = t('Questions')

- if @questions.any?
  table.table.table-hover.table-bordered
    thead
      tr.text-center
        th = t('.title')
        th = t('.body')
        th = t('.actions')

    tbody
      - @questions.each do |question|
        tr
          td style="text-align: center;" = question.title
          td style="text-align: center;" = question.body
          td style="text-align: center;" = link_to t('.show'), question_path(question)
- else
  p = 'No questions asked yet.'

app/views/questions/new.html.slim
= render 'form', question: @question

app/views/questions/show.html.slim
= render @question, badge: @badge


h2 Answers:
.answers
  = render 'answers/answers_index', best_answer: @best_answer, other_answers: @other_answers

= render 'answers/form', question: @question, answer: @answer

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.question').html('<%= j render @question, badge: @question.badge %>');

  loadGists('.gist-link');
<% end %>