config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up, to: 'votes#vote_up'
      post :vote_down, to: 'votes#vote_down'
      delete :unvote, to: 'votes#unvote'
    end
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        patch :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :badges, only: %i[destroy index]
end

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |msg|
      li = msg

app/views/shared/_files_attachment.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div id="file_container_#{file.id}" class="file-container"
      - if file.representable?
        = link_to url_for(file) do
          = image_tag file.variant(resize_to_limit: [50, 50])
      - else
        p= link_to file.filename.to_s, url_for(file)

      - if author?(current_user, resource)
        = button_to "Remove file",
                attachment_path(file),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                remote: true

app/views/shared/_flashes.html.slim
.flash_notice
  - if flash[:notice]
    = flash[:notice]
.flash_alert
  - if flash[:alert]
    = flash[:alert]

app/views/shared/_links_attachment.html.slim
.links
  - if resource.links.any?
    p Links:
    ul
      - resource.links.each do |link|
        - if link.url.include?("gist.github.com")
          - gist_id = link.url.split('/').last # Извлекаем gist_id из URL
          li= link_to link.name, link.url, class: 'gist-link', data: { gist_id: gist_id }
        - else
          li= link_to link.name, link.url

app/views/shared/_nav.html.slim
nav.navbar style="background-color: #e3f2fd;"
  .navbar-text.px-4
    - if user_signed_in?
      = button_to t('Sign out'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary btn-sm', data: { turbolinks: false }
      = link_to "My badges", badges_path, class: 'nav-link'
    - else
      = button_to t('Log in'), new_user_session_path
      = button_to t('Sign up'), new_user_registration_path

app/views/shared/_votes.html.slim
- if resource.present?
  .votes
    .rating
      = resource.rating

    .rating-errors

    - unless author?(current_user, resource)
      p class="vote" style="#{'display: none;' if resource.voted_by?(current_user)}"
        = link_to "Vote up", polymorphic_path(resource, action: :vote_up), remote: true, method: :post, data: { type: :json }
        = " | "
        = link_to "Vote down", polymorphic_path(resource, action: :vote_down), remote: true, method: :post, data: { type: :json }
      p class="delete-vote" style="#{'display: none;' unless resource.voted_by?(current_user)}"
        = link_to "delete vote", polymorphic_path(resource, action: :unvote), remote: true, method: :delete, data: { type: :json }