config/routes.rb
Rails.application.routes.draw do
  concern :votable do
    member do
      post :vote_up, to: 'votes#vote_up'
      post :vote_down, to: 'votes#vote_down'
      delete :unvote, to: 'votes#unvote'
    end
  end

  devise_for :users

  root to: 'questions#index'

  resources :questions, concerns: :votable do
    resources :answers, concerns: :votable, shallow: true do
      member do
        patch :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :badges, only: %i[destroy index]
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable

  belongs_to :question
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  scope :kept, -> { where(discarded_at: nil) }

  def soft_delete
    update(discarded_at: Time.current)
  end

  def mark_as_best
    question.update(best_answer_id: id)
    award_badge_to_user
  end

  private

  def award_badge_to_user
    return unless question.badge

    user.badges << question.badge
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[show edit update destroy mark_as_best]
  before_action :set_question, only: %i[index new create]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @answers = @question.answers.kept
  end

  def new
    @answer = @question.answers.new
    @answer.links.build # or @answer.links.new
  end

  def show; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      render_success_message(@answer)
    else
      render_error_message(@answer)
    end
  end

  def edit; end

  def update
    @answer.update(answer_params) if current_user.author?(@answer)

    set_answers_data
  end

  def destroy
    @answer.soft_delete if current_user.author?(@answer)
  end

  def mark_as_best
    @answer.mark_as_best

    set_answers_data
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def set_answers_data
    @question = @answer.question
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @best_answer).kept
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   files: [],
                                   links_attributes: %i[id name url _destroy])
  end

  def render_success_message(answer)
    attachments = format_attachments(answer.files)

    render json: { id: answer.id, body: answer.body, attachments: }, status: :created
  end

  def render_error_message(answer)
    render json: answer.errors.full_messages, status: :unprocessable_entity
  end

  def format_attachments(files)
    files.map do |file|
      {
        url: url_for(file),
        filename: file.filename.to_s
      }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id="answer-#{answer.id}" class="answer"
  p
    | Answered by:
    = answer.user.email
  p
    | Created at:
    = answer.created_at.strftime("%Y-%m-%d %H:%M")
  p
    | Rating:
    = render "shared/votes", resource: answer
  p
    = answer.body
  p
    = render 'shared/files_attachment', resource: answer

  = render 'shared/links_attachment', resource: answer

  = render 'shared/answers/answer_controls', answer: answer, question: @question, best_answer: @best_answer

app/views/answers/_answers_index.html.slim
= render 'answers/best_answer', best_answer: best_answer

- other_answers.each do |answer|
  = render 'answers/answer', answer: answer

app/views/answers/_best_answer.html.slim
- if best_answer.present?
  div id="answer-#{best_answer.id}" class="best-answer"
    h3
      | Best answer:
    p
      | Answered by:
      = best_answer.user.email
    p
      | Created at:
      = best_answer.created_at.strftime("%Y-%m-%d %H:%M")
    p
      | Rating:
      = render "shared/votes", resource: best_answer
    p
      = best_answer.body
    p
      = render 'shared/files_attachment', resource: best_answer

    = render 'shared/links_attachment', resource: best_answer

    = render 'shared/answers/answer_controls', answer: best_answer, question: @question, best_answer: @best_answer

app/views/answers/_form.html.slim
h3 Write an Answer:

= form_with(model: [question, answer], local: false, remote: true, data: { type: :json }, class: 'new-answer') do |form|
  .answer-errors
    = render 'shared/errors', resource: answer
  .field
    p
      = form.label :body
      = form.text_area :body
    p
      = form.label :files
      = form.file_field :files, multiple: true

    p
    .links
      = link_to_add_association 'Add link', form, :links

  .actions
    p
      = form.submit 'Answer'
p
  = link_to 'Back', questions_path, remote: true

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name

    = f.label :url, 'Url'
    = f.text_field :url
  = link_to_remove_association 'Remove link', f

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render 'answers/answers_index', best_answer: @best_answer, other_answers: @other_answers %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers').html('<%= j render 'answers/answers_index', best_answer: @best_answer, other_answers: @other_answers %>');

  loadGists('.gist-link');
<% end %>